Repository OZimbres/To-Do-List, pull requests merged in 2023-10, with the labels that each got.

#11 Starting project
  bin/ToDoList.class
  src/ToDoList.java
Labels: enhancement, Mandatory Criteria

#13 Tzc branch
  bin/App.class
  bin/ToDoList$1.class
  bin/ToDoList.class
  src/ToDoList.java
Labels: enhancement, Mandatory Criteria

#14 Tzc branch
  bin/App.class
  bin/ToDoList$1.class
  bin/ToDoList$2.class
  bin/ToDoList$3.class
  bin/ToDoList.class
  src/App.java
  src/ToDoList.java
Labels: enhancement, Mandatory Criteria

#15 Adding Try-Catch
  bin/App.class
  bin/TaskControl.class
  bin/ToDoList$1.class
  bin/ToDoList$2.class
  bin/ToDoList$3.class
  bin/ToDoList.class
  src/TaskControl.java
  src/ToDoList.java
Labels: enhancement, Desirable Criteria

#16 Project Finished
  bin/App.class
  bin/Task.class
  bin/TaskControl.class
  bin/ToDoList$1.class
  bin/ToDoList$2.class
  bin/ToDoList$3.class
  bin/ToDoList.class
  src/Task.java
  src/TaskControl.java
  src/ToDoList.java
Labels: Desirable Criteria

#17 Nova Funcionalidade
  bin/EditTask$1.class
  bin/EditTask.class
  bin/Task.class
  bin/TaskControl.class
  bin/ToDoList$1.class
  bin/ToDoList$2.class
  bin/ToDoList$3.class
  bin/ToDoList.class
  src/EditTask.java
  src/Task.java
  src/TaskControl.java
  src/ToDoList.java
Labels: Desirable Criteria
